name: Build and push Docker image

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # 수동 실행 가능

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate tag (YYYYMMDD-RUN_NUMBER)
        id: tag
        run: echo "value=$(date +%Y%m%d)-${{ github.run_number }}" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/pocketbase:latest
            ghcr.io/${{ github.repository_owner }}/pocketbase:${{ steps.tag.outputs.value }}
          build-args: |
            PB_VERSION=${{ secrets.PB_VERSION }}
